language: java
install: cd App; ant deps; cd -
before_script:
 - mysql -e 'create database IF NOT EXISTS myapp_test;'
  'use myapp_test;'
  'create table employee(id int, name varchar(20), company varchar(20));'
  'insert into employee values (100, "Manju", "verizon");'
  'insert into employee values (101, "Vignesh", "verizon");'
  'insert into employee values (102, "JaganR", "verizon");'
script: cd App; ant main; cd -
jdk:
  - oraclejdk7
  - oraclejdk8
services:
  - mysql
deploy:
   edge: true
   provider: cloudfoundry
   username: jagan.kumar.rajamani@verizon.com
   password: verizon1
   api: https://api.run.pivotal.io
   organization: jag.org
   space: development  

